### PR TITLE
fix: use latest ghcommit and fix cwd for git-cli

### LINKED ISSUE #475: Remove usage of `process.chdir()`
See: https://github.com/changesets/action/pull/473#discussion_r2081314357

As of #473, we now explicitly set the `cwd` argument for all subprocess calls. As such, it shouldn't be necessary to change the working directory of the current process.

We need to ensure that usage of `commitChangesFromRepo` (which makes a call to `process.cwd()`) also works correctly for our use-cases before we can remove this process call.

Namely, we need a way for running this action to work when:

- a repository is checked-out into a sub-directory.
- `cwd` is set to a subdirectory of that subdirectory

In particular, we should:

* Update `commitChangesFromRepo` so that `repoDirectory` can be used to recursively start a search for the root of a repository.
* Specify `repoDirectory` to be explicit `cwd`, as with `addFromDirectory`.

### PR DESCRIPTION
**Pull request by s0**
- `cwd` was not working correctly when commitMode was set to `git-cli`, as it was attempting to resolve the `cwd` twice. (This problem only occured when specifying a relative path for `cwd`.)
- Update `ghcommit`, and avoid calling `process.chdir()` to change the working directory. Instead, we now pass the `cwd` option everywhere.

fixes #475

### CODE REVIEW

**Comment by s0** [comment]
@Andarist please take a look and review.

File: src/index.ts [hunk 1]
```diff
@@ -16,12 +17,7 @@ const getOptionalInput = (name: string) => core.getInput(name) || undefined;
     return;
   }
 
-  const inputCwd = getOptionalInput("cwd");
-  if (inputCwd) {
-    core.info("changing directory to the one given as the input");
-    process.chdir(inputCwd);
-  }
-  const cwd = inputCwd || process.cwd();
+  const cwd = path.resolve(getOptionalInput("cwd") ?? "");
```
Comment (Andarist) [inline src/index.ts:20]: @s0 I have simplified this slightly, this should still be equivalent, right? `path.resolve` already takes `process.cwd()` into account by default

Comment (s0) [reply src/index.ts:20]:
```
~ > node
> require('path').resolve('')
'/home/sam'
```

LGTM!

**Review by s0 — COMMENTED** [review]
Changes LGTM

File: .changeset/lemon-garlics-sell.md [hunk 2]
```diff
@@ -0,0 +1,9 @@
+---
+"@changesets/action": patch
+---
+
+fix: cwd now works again with relative paths and commitMode: git-cli
```
Comment (Andarist) [inline .changeset/lemon-garlics-sell.md:5]:
```suggestion
`cwd` now works again with relative paths and `commitMode: git-cli`
```

File: .changeset/lemon-garlics-sell.md [hunk 3]
```diff
@@ -0,0 +1,9 @@
...
+
+v1.5.2 introduced a bug where specifying `cwd`
+when using the default `commitMode` would break things,
+as it tried to resolve the path twice.
```
Comment (Andarist) [inline .changeset/lemon-garlics-sell.md:9]:
```suggestion
```

File: .changeset/sour-elephants-switch.md [hunk 4]
```diff
@@ -0,0 +1,7 @@
+---
+"@changesets/action": patch
+---
+
+Update @changesets/ghcommit, and avoid calling `process.chdir()`
+
+fixes #475
```
Comment (Andarist) [inline .changeset/sour-elephants-switch.md:7]:
```suggestion
---
---
```

**Comment by oshytiko** [comment]
I think this fix uncovered another issue, could someone take a look at [this PR](https://github.com/changesets/action/pull/502) please!

ping @s0 @Andarist
