### PR TITLE
fix: use status when http err

### LINKED ISSUE #446: Deprecation: [@octokit/request-error] `error.code` is deprecated, use `error.status`.
Image

Deprecation: [@octokit/request-error] `error.code` is deprecated, use `error.status`.
    at RequestError.get (/home/runner/work/_actions/changesets/action/v1/dist/index.js:1:300089)
    at createRelease (/home/runner/work/_actions/changesets/action/v1/dist/index.js:63:79970)
    at async Promise.all (index 1)
    at async runPublish (/home/runner/work/_actions/changesets/action/v1/dist/index.js:63:80620)
    at async /home/runner/work/_actions/changesets/action/v1/dist/index.js:63:76759
Error: HttpError: Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"}
Error: Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"}

### PR DESCRIPTION
**Pull request by nayounsang**
close #446 

For [@octokit/request-err](https://github.com/octokit/request-error.js/blob/main/src/index.ts) err, use `err.status`.
Add error handling for this issue.

### CODE REVIEW

**Comment by nayounsang** [comment]
Wait, is it okay to "ignore" this error? It seems like it would be okay to just let it pop up.
So convert to draft.

File: src/run.ts [hunk 1]
```diff
@@ -88,8 +88,11 @@ const createRelease = async (
     if (
       err &&
       typeof err === "object" &&
-      "code" in err &&
-      err.code !== "ENOENT"
```
Comment (Andarist) [inline src/run.ts:92]: This has never meant to target `RequestError` but rather the errors potentially coming from `fs.readFile`. I think the proper fix would be only to wrap what we have to wrap with `try/catch`.

Comment (nayounsang) [reply src/run.ts:57]: Thx for review & work!
